/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 15:22:46 GMT 2024
 */

package uk.ac.sheffield.com1003.cafe.exceptions;

import org.junit.Test;

import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.exceptions.TooManyIngredientsException;

public class TooManyIngredientsException_ESTest {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        TooManyIngredientsException tooManyIngredientsException0 = new TooManyIngredientsException();
    }
}
