/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 26 17:30:22 GMT 2023
 */

package uk.ac.sheffield.com1003.cafe.evosuite.branch.ingredients;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.ingredients.Milk;
import uk.ac.sheffield.com1003.cafe.ingredients.Unit;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Milk_ESTest extends Milk_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Milk.Type milk_Type0 = Milk.Type.ALMOND;
      Milk milk0 = new Milk((-387), milk_Type0);
      Milk milk1 = new Milk((-387));
      boolean boolean0 = milk1.equals(milk0);
      assertEquals("Milk", milk1.getName());
      assertFalse(boolean0);
      assertEquals((-387), milk1.getAmount());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Milk milk0 = new Milk();
      Milk milk1 = new Milk();
      assertTrue(milk1.equals(milk0));
      
      boolean boolean0 = milk1.equals(milk0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Milk.Type milk_Type0 = Milk.Type.ALMOND;
      Milk milk0 = new Milk((-387), milk_Type0);
      Milk milk1 = new Milk();
      boolean boolean0 = milk0.equals(milk1);
      assertFalse(boolean0);
      assertEquals("Milk", milk1.getName());
      assertEquals(100, milk1.getAmount());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Milk.Type milk_Type0 = Milk.Type.ALMOND;
      Milk milk0 = new Milk((-387), milk_Type0);
      Milk milk1 = new Milk();
      assertEquals("Milk", milk1.getName());
      
//      milk1.name = "lt= -ifPY=')zh";
      boolean boolean0 = milk0.equals(milk1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Milk.Type milk_Type0 = Milk.Type.ALMOND;
      Milk milk0 = new Milk((-387), milk_Type0);
      boolean boolean0 = milk0.equals(milk_Type0);
      assertEquals((-387), milk0.getAmount());
      assertFalse(boolean0);
      assertEquals("Milk", milk0.getName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Milk.Type milk_Type0 = Milk.Type.ALMOND;
      Milk milk0 = new Milk((-387), milk_Type0);
      boolean boolean0 = milk0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals((-387), milk0.getAmount());
      assertEquals("Milk", milk0.getName());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Milk milk0 = new Milk();
      boolean boolean0 = milk0.equals(milk0);
      assertEquals(100, milk0.getAmount());
      assertEquals("Milk", milk0.getName());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Milk.Type milk_Type0 = Milk.Type.ALMOND;
      Milk milk0 = new Milk((-387), milk_Type0);
      String string0 = milk0.toString();
      assertEquals("Milk [unit=ML, amount=-387, type=ALMOND]", string0);
      assertEquals("Milk", milk0.getName());
  }
}
