/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 26 14:43:56 GMT 2023
 */

package uk.ac.sheffield.com1003.cafe.evosuite.branch.ingredients;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.ingredients.Unit;
import uk.ac.sheffield.com1003.cafe.ingredients.Water;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Water_ESTest extends Water_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Water water0 = new Water();
      Water water1 = new Water();
      boolean boolean0 = water0.equals(water1);
      assertEquals("Water", water1.getName());
      assertEquals(30, water1.getAmount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Water water0 = new Water(1);
      Water water1 = new Water();
      boolean boolean0 = water0.equals(water1);
      assertFalse(boolean0);
      assertEquals(30, water1.getAmount());
      assertEquals("Water", water1.getName());
      assertFalse(water1.equals((Object)water0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Water water0 = new Water(1);
      assertEquals("Water", water0.getName());
      Water water1 = new Water(1);
      boolean boolean0 = water0.equals(water1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Water water0 = new Water(1);
      boolean boolean0 = water0.equals(water0);
      assertTrue(boolean0);
      assertEquals(1, water0.getAmount());
      assertEquals("Water", water0.getName());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Water water0 = new Water();
      boolean boolean0 = water0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals(30, water0.getAmount());
      assertEquals("Water", water0.getName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Water water0 = new Water();
      String string0 = water0.toString();
      assertEquals("Water [unit=ML, amount=30]", string0);
      assertEquals("Water", water0.getName());
  }
}
