/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 16:06:42 GMT 2024
 */

package uk.ac.sheffield.com1003.cafe;

import org.junit.Test;

import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.App;

public class App_ESTest {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        String[] stringArray0 = new String[2];
        App.main(stringArray0);
        assertEquals(2, stringArray0.length);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        App app0 = new App();
    }
}
