/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 26 12:54:18 GMT 2023
 */

package uk.ac.sheffield.com1003.cafe.ingredients;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.ingredients.Coffee;
import uk.ac.sheffield.com1003.cafe.ingredients.Unit;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Coffee_ESTest extends Coffee_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Coffee coffee0 = new Coffee(1, true);
      Coffee coffee1 = new Coffee(0);
      boolean boolean0 = coffee0.equals(coffee1);
      assertFalse(boolean0);
      assertEquals(1, coffee0.getAmount());
      assertEquals("Coffee", coffee1.getName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Coffee coffee0 = new Coffee();
      coffee0.name = null;
      // Undeclared exception!
      try { 
        coffee0.equals(coffee0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Coffee coffee0 = new Coffee((-2539), true);
      Coffee coffee1 = new Coffee((-2539));
      boolean boolean0 = coffee0.equals(coffee1);
      assertEquals((-2539), coffee1.getAmount());
      assertFalse(boolean0);
      assertEquals("Coffee", coffee1.getName());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Coffee coffee0 = new Coffee((-2539), true);
      Coffee coffee1 = new Coffee();
      boolean boolean0 = coffee0.equals(coffee1);
      assertFalse(boolean0);
      assertEquals("Coffee", coffee1.getName());
      assertEquals(8, coffee1.getAmount());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Coffee coffee0 = new Coffee((-2539), true);
      Coffee coffee1 = new Coffee();
      assertEquals("Coffee", coffee1.getName());
      
      coffee1.name = "Coffee [unit=GR, amount=-2539, decaf=true]";
      boolean boolean0 = coffee0.equals(coffee1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Coffee coffee0 = new Coffee((-2539), true);
      boolean boolean0 = coffee0.equals("Coffee [unit=GR, amount=-2539, decaf=true]");
      assertEquals((-2539), coffee0.getAmount());
      assertEquals("Coffee", coffee0.getName());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Coffee coffee0 = new Coffee((-2539), true);
      boolean boolean0 = coffee0.equals(coffee0);
      assertEquals("Coffee", coffee0.getName());
      assertEquals((-2539), coffee0.getAmount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Coffee coffee0 = new Coffee(1, true);
      boolean boolean0 = coffee0.equals((Object) null);
      assertEquals("Coffee", coffee0.getName());
      assertEquals(1, coffee0.getAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Coffee coffee0 = new Coffee((-2539), true);
      String string0 = coffee0.toString();
      assertEquals("Coffee", coffee0.getName());
      assertEquals("Coffee [unit=GR, amount=-2539, decaf=true]", string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Coffee coffee0 = new Coffee();
      Coffee coffee1 = new Coffee();
      assertTrue(coffee1.equals((Object)coffee0));
      
      Unit unit0 = Unit.ML;
      coffee1.unit = unit0;
      boolean boolean0 = coffee0.equals(coffee1);
      assertFalse(boolean0);
  }
}
