/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 26 12:56:31 GMT 2023
 */

package uk.ac.sheffield.com1003.cafe.ingredients;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.ingredients.Milk;
import uk.ac.sheffield.com1003.cafe.ingredients.Unit;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Milk_ESTest extends Milk_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Milk.Type milk_Type0 = Milk.Type.SKIMMED;
      Milk milk0 = new Milk(4, milk_Type0);
      Milk milk1 = new Milk();
      boolean boolean0 = milk0.equals(milk1);
      assertEquals(100, milk1.getAmount());
      assertEquals("Milk", milk1.getName());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Milk milk0 = new Milk();
      milk0.name = null;
      // Undeclared exception!
      try { 
        milk0.equals(milk0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Milk milk0 = new Milk(1);
      Milk.Type milk_Type0 = Milk.Type.SEMI;
      Milk milk1 = new Milk(1, milk_Type0);
      boolean boolean0 = milk1.equals(milk0);
      assertFalse(boolean0);
      assertEquals(1, milk1.getAmount());
      assertEquals("Milk", milk1.getName());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Milk milk0 = new Milk();
      Unit unit0 = Unit.UNDEFINED;
      milk0.unit = unit0;
      Milk milk1 = new Milk();
      boolean boolean0 = milk0.equals(milk1);
      assertEquals(100, milk1.getAmount());
      assertEquals("Milk", milk1.getName());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Milk milk0 = new Milk();
      Milk milk1 = new Milk(1);
      boolean boolean0 = milk0.equals(milk1);
      assertFalse(boolean0);
      assertEquals(1, milk1.getAmount());
      assertFalse(milk1.equals((Object)milk0));
      assertEquals("Milk", milk1.getName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Milk milk0 = new Milk();
      assertEquals("Milk", milk0.getName());
      
      milk0.name = "$VALUES";
      Milk milk1 = new Milk();
      boolean boolean0 = milk0.equals(milk1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Milk.Type milk_Type0 = Milk.Type.SKIMMED;
      Milk milk0 = new Milk(3, milk_Type0);
      Object object0 = new Object();
      boolean boolean0 = milk0.equals(object0);
      assertFalse(boolean0);
      assertEquals("Milk", milk0.getName());
      assertEquals(3, milk0.getAmount());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Milk milk0 = new Milk();
      boolean boolean0 = milk0.equals(milk0);
      assertTrue(boolean0);
      assertEquals(100, milk0.getAmount());
      assertEquals("Milk", milk0.getName());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Milk milk0 = new Milk();
      boolean boolean0 = milk0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals("Milk", milk0.getName());
      assertEquals(100, milk0.getAmount());
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Milk milk0 = new Milk(1);
      String string0 = milk0.toString();
      assertEquals("Milk [unit=ML, amount=1, type=WHOLE]", string0);
      assertEquals("Milk", milk0.getName());
  }
}
