/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 07 15:43:14 GMT 2024
 */

package uk.ac.sheffield.com1003.cafe.ingredients;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.ingredients.Milk;
import uk.ac.sheffield.com1003.cafe.ingredients.Unit;

//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Milk_ESTest {

//  @org.junit.Rule
//  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();
//
//  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone();
//
//  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);
//
//
//  @BeforeClass
//  public static void initEvoSuiteFramework() {
//    org.evosuite.runtime.RuntimeSettings.className = "uk.ac.sheffield.com1003.cafe.ingredients.Milk";
//    org.evosuite.runtime.GuiSupport.initialize();
//    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
//    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
//    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
//    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
//    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
//    org.evosuite.runtime.classhandling.JDKClassResetter.init();
//    setSystemProperties();
//    initializeClasses();
//    org.evosuite.runtime.Runtime.getInstance().resetRuntime();
//  }
//
//  @AfterClass
//  public static void clearEvoSuiteFramework(){
//    Sandbox.resetDefaultSecurityManager();
//    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
//  }
//
//  @Before
//  public void initTestCase(){
//    threadStopper.storeCurrentThreads();
//    threadStopper.startRecordingTime();
//    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
//    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
//    setSystemProperties();
//    org.evosuite.runtime.GuiSupport.setHeadless();
//    org.evosuite.runtime.Runtime.getInstance().resetRuntime();
//    org.evosuite.runtime.agent.InstrumentingAgent.activate();
//  }
//
//  @After
//  public void doneWithTestCase(){
//    threadStopper.killAndJoinClientThreads();
//    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
//    org.evosuite.runtime.classhandling.JDKClassResetter.reset();
//    resetClasses();
//    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
//    org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
//    org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
//  }
//
//  public static void setSystemProperties() {
//
//    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
//    java.lang.System.setProperty("user.dir", "/Users/ruizhengu/Experiments/model_solution_evosuite");
//    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/1r/t1t8tcs944979hxkq3w8p1b40000gn/T/");
//  }
//
//  private static void initializeClasses() {
//    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Milk_ESTest.class.getClassLoader() ,
//      "uk.ac.sheffield.com1003.cafe.ingredients.Ingredient",
//      "uk.ac.sheffield.com1003.cafe.ingredients.Milk",
//      "uk.ac.sheffield.com1003.cafe.ingredients.Milk$Type",
//      "uk.ac.sheffield.com1003.cafe.ingredients.Unit"
//    );
//  }
//
//  private static void resetClasses() {
//    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Milk_ESTest.class.getClassLoader());
//
//    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
//      "uk.ac.sheffield.com1003.cafe.ingredients.Ingredient",
//      "uk.ac.sheffield.com1003.cafe.ingredients.Milk",
//      "uk.ac.sheffield.com1003.cafe.ingredients.Milk$Type",
//      "uk.ac.sheffield.com1003.cafe.ingredients.Unit"
//    );
//  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Milk milk0 = new Milk((-688));
      Milk.Type milk_Type0 = Milk.Type.WHOLE;
      Milk milk1 = new Milk(71, milk_Type0);
      boolean boolean0 = milk0.equals(milk1);
      assertEquals("Milk", milk1.getName());
      assertFalse(boolean0);
      assertEquals(71, milk1.getAmount());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Milk milk0 = new Milk();
      milk0.name = null;
      // Undeclared exception!
      try { 
        milk0.equals(milk0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Milk milk0 = new Milk((-1091196985));
      Milk.Type milk_Type0 = Milk.Type.SEMI;
      Milk milk1 = new Milk((-1091196985), milk_Type0);
      boolean boolean0 = milk0.equals(milk1);
      assertEquals("Milk", milk1.getName());
      assertFalse(boolean0);
      assertEquals((-1091196985), milk1.getAmount());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Milk milk0 = new Milk();
      Unit unit0 = Unit.GR;
      milk0.unit = unit0;
      Milk milk1 = new Milk();
      boolean boolean0 = milk0.equals(milk1);
      assertEquals("Milk", milk1.getName());
      assertEquals(100, milk1.getAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Milk milk0 = new Milk();
      Milk.Type milk_Type0 = Milk.Type.WHOLE;
      Milk milk1 = new Milk(2, milk_Type0);
      boolean boolean0 = milk0.equals(milk1);
      assertEquals("Milk", milk1.getName());
      assertFalse(boolean0);
      assertEquals(2, milk1.getAmount());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Milk milk0 = new Milk();
      Milk milk1 = new Milk();
      assertEquals("Milk", milk1.getName());
      
      milk1.name = "C";
      boolean boolean0 = milk0.equals(milk1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Milk milk0 = new Milk();
      Object object0 = new Object();
      boolean boolean0 = milk0.equals(object0);
      assertFalse(boolean0);
      assertEquals(100, milk0.getAmount());
      assertEquals("Milk", milk0.getName());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Milk milk0 = new Milk();
      boolean boolean0 = milk0.equals((Object) null);
      assertEquals(100, milk0.getAmount());
      assertEquals("Milk", milk0.getName());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Milk milk0 = new Milk((-1091196985));
      boolean boolean0 = milk0.equals(milk0);
      assertEquals("Milk", milk0.getName());
      assertEquals((-1091196985), milk0.getAmount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Milk milk0 = new Milk();
      String string0 = milk0.toString();
      assertEquals("Milk", milk0.getName());
      assertEquals("Milk [unit=ML, amount=100, type=WHOLE]", string0);
  }
}
