/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 14:58:17 GMT 2024
 */

package uk.ac.sheffield.com1003.cafe.ingredients;

import org.junit.Test;

import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.ingredients.Coffee;
import uk.ac.sheffield.com1003.cafe.ingredients.Unit;

public class Coffee_ESTest {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        Coffee coffee0 = new Coffee(2);
        Coffee coffee1 = new Coffee();
        boolean boolean0 = coffee0.equals(coffee1);
        assertEquals(8, coffee1.getAmount());
        assertFalse(boolean0);
        assertEquals("Coffee", coffee1.getName());
        assertFalse(coffee1.equals((Object) coffee0));
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        Coffee coffee0 = new Coffee();
        coffee0.name = null;
        // Undeclared exception!
        try {
            coffee0.equals(coffee0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
        }
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        Coffee coffee0 = new Coffee();
        Coffee coffee1 = new Coffee(8, true);
        boolean boolean0 = coffee0.equals(coffee1);
        assertEquals("Coffee", coffee1.getName());
        assertFalse(boolean0);
        assertEquals(8, coffee1.getAmount());
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        Coffee coffee0 = new Coffee();
        Coffee coffee1 = new Coffee();
        assertTrue(coffee1.equals((Object) coffee0));

        Unit unit0 = Unit.UNDEFINED;
        coffee1.unit = unit0;
        boolean boolean0 = coffee0.equals(coffee1);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test4() throws Throwable {
        Coffee coffee0 = new Coffee();
        Coffee coffee1 = new Coffee((-1120));
        boolean boolean0 = coffee0.equals(coffee1);
        assertEquals("Coffee", coffee1.getName());
        assertEquals((-1120), coffee1.getAmount());
        assertFalse(boolean0);
        assertFalse(coffee1.equals((Object) coffee0));
    }

    @Test(timeout = 4000)
    public void test5() throws Throwable {
        Coffee coffee0 = new Coffee();
        Coffee coffee1 = new Coffee();
        assertEquals("Coffee", coffee1.getName());

        coffee1.name = ")UBQn:0";
        boolean boolean0 = coffee0.equals(coffee1);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test6() throws Throwable {
        Coffee coffee0 = new Coffee(2);
        Object object0 = new Object();
        boolean boolean0 = coffee0.equals(object0);
        assertEquals("Coffee", coffee0.getName());
        assertFalse(boolean0);
        assertEquals(2, coffee0.getAmount());
    }

    @Test(timeout = 4000)
    public void test7() throws Throwable {
        Coffee coffee0 = new Coffee();
        boolean boolean0 = coffee0.equals(coffee0);
        assertEquals(8, coffee0.getAmount());
        assertTrue(boolean0);
        assertEquals("Coffee", coffee0.getName());
    }

    @Test(timeout = 4000)
    public void test8() throws Throwable {
        Coffee coffee0 = new Coffee((-1), true);
        String string0 = coffee0.toString();
        assertEquals("Coffee [unit=GR, amount=-1, decaf=true]", string0);
        assertEquals("Coffee", coffee0.getName());
    }

    @Test(timeout = 4000)
    public void test9() throws Throwable {
        Coffee coffee0 = new Coffee();
        boolean boolean0 = coffee0.equals((Object) null);
        assertEquals("Coffee", coffee0.getName());
        assertEquals(8, coffee0.getAmount());
        assertFalse(boolean0);
    }
}
