/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 14:57:11 GMT 2024
 */

package uk.ac.sheffield.com1003.cafe.ingredients;

import org.junit.Test;

import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.ingredients.Syrup;

public class Syrup_ESTest {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        Syrup syrup0 = new Syrup();
        String string0 = syrup0.toString();
        assertEquals("Syrup [unit=ML, amount=10, flavour=Plain]", string0);
        assertEquals("Syrup", syrup0.getName());
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        Syrup syrup0 = new Syrup("Plain");
        assertEquals("Syrup", syrup0.getName());
        assertEquals(10, syrup0.getAmount());
    }
}
