/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 21 22:17:03 GMT 2023
 */

package uk.ac.sheffield.com1003.cafe.evosuite.original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.Order;
import uk.ac.sheffield.com1003.cafe.Recipe;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Order_ESTest extends Order_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Recipe.Size recipe_Size0 = Recipe.Size.SMALL;
      Recipe recipe0 = new Recipe((String) null, (-1964.354650664), recipe_Size0, 1);
      Order order0 = new Order(recipe0, (String) null, 1608.0207858161002, (String) null);
      String string0 = order0.toString();
      assertEquals("Order: null; For: null; Paid: 1608.0207858161002", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Order order0 = new Order((Recipe) null, "%9ed#wMSU}9QR>", 1537.7573);
      // Undeclared exception!
      try { 
        order0.printReceipt();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sheffield.com1003.cafe.Order", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Recipe.Size recipe_Size0 = Recipe.Size.LARGE;
      Recipe recipe0 = new Recipe("66dtBv'", 0.0, recipe_Size0, 1336);
      Order order0 = new Order(recipe0, "^_", 341.7578235715, "line.separator");
      order0.printReceipt();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Recipe.Size recipe_Size0 = Recipe.Size.SMALL;
      Recipe recipe0 = new Recipe((String) null, (-1964.354650664), recipe_Size0, 1);
      Order order0 = new Order(recipe0, (String) null, 1608.0207858161002, (String) null);
      order0.serve();
      order0.printReceipt();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Order order0 = new Order((Recipe) null, "%9ed#wMSU}9QR>", 1537.7573);
      // Undeclared exception!
      try { 
        order0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sheffield.com1003.cafe.Order", e);
      }
  }
}
