/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 04 16:46:45 GMT 2024
 */

package uk.ac.sheffield.com1003.cafe;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Order_ESTest extends Order_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Recipe recipe0 = new Recipe("GY/:x%f9;@w3{5znpC:", 0.0);
      Order order0 = new Order(recipe0, "Coffee [unit=", 0.0);
      String string0 = order0.toString();
      assertEquals("Order: GY/:x%f9;@w3{5znpC:; For: Coffee [unit=; Paid: 0.0", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Order order0 = new Order((Recipe) null, "%d", 628.0030285051);
      // Undeclared exception!
      try { 
        order0.printReceipt();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sheffield.com1003.cafe.Order", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Recipe recipe0 = new Recipe("GY/:x%f9;@w3{5znpC:", 0.0);
      Order order0 = new Order(recipe0, "Coffee [unit=", 0.0);
      order0.printReceipt();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Recipe recipe0 = new Recipe("GY/:x%f9;@w3{5znpC:", (-1.09993848021331));
      Order order0 = new Order(recipe0, "GY/:x%f9;@w3{5znpC:", (-1.09993848021331));
      order0.serve();
      order0.printReceipt();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Recipe recipe0 = new Recipe("@4hh==MTpF]#:C]qS", (-699.6573));
      Order order0 = new Order(recipe0, "", 0.0, "");
      order0.serve();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Order order0 = new Order((Recipe) null, "%d", 1.0, "%d");
      // Undeclared exception!
      try { 
        order0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("uk.ac.sheffield.com1003.cafe.Order", e);
      }
  }
}
