/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 04 16:43:23 GMT 2024
 */

package uk.ac.sheffield.com1003.cafe.ingredients;

import org.junit.Test;
import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Ingredient_ESTest extends Ingredient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Milk.Type milk_Type0 = Milk.Type.WHOLE;
      Milk milk0 = new Milk(0, milk_Type0);
      String string0 = milk0.toString();
      assertEquals("Milk [unit=ML, amount=0, type=WHOLE]", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Syrup syrup0 = new Syrup("uk.ac.sheffield.com1003.cafe.ingredients.Ingredient");
      syrup0.name = null;
      String string0 = syrup0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Coffee coffee0 = new Coffee(8, true);
      coffee0.name = "$VALUES";
      coffee0.name = "E7SR*x^vx,(3";
      coffee0.name = "";
      String string0 = coffee0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Milk.Type milk_Type0 = Milk.Type.WHOLE;
      Milk milk0 = new Milk(0, milk_Type0);
      int int0 = milk0.getAmount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Coffee coffee0 = new Coffee();
      coffee0.amount = (-2914);
      int int0 = coffee0.getAmount();
      assertEquals((-2914), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Syrup syrup0 = new Syrup("uk.ac.sheffield.com1003.cafe.ingredients.Ingredient");
      syrup0.name = null;
      Coffee coffee0 = new Coffee(0, true);
      // Undeclared exception!
      try { 
        syrup0.equals(coffee0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Syrup syrup0 = new Syrup();
      String string0 = syrup0.getName();
      assertEquals("Syrup", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Syrup syrup0 = new Syrup();
      Object object0 = new Object();
      boolean boolean0 = syrup0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Syrup syrup0 = new Syrup();
      boolean boolean0 = syrup0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Water water0 = new Water();
      Unit unit0 = water0.getUnit();
      assertEquals(Unit.ML, unit0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Milk milk0 = new Milk();
      int int0 = milk0.getAmount();
      assertEquals(100, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Syrup syrup0 = new Syrup();
      boolean boolean0 = syrup0.equals(syrup0);
      assertTrue(boolean0);
  }
}
