/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 07 11:37:24 GMT 2024
 */

package uk.ac.sheffield.com1003.cafe.ingredients;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.ingredients.Syrup;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Syrup_ESTest extends Syrup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Syrup syrup0 = new Syrup();
      String string0 = syrup0.toString();
      assertEquals("Syrup", syrup0.getName());
      assertEquals("Syrup [unit=ML, amount=10, flavour=Plain]", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Syrup syrup0 = new Syrup("|yQ;X:YD%5!V@VQy5k");
      assertEquals(10, syrup0.getAmount());
      assertEquals("Syrup", syrup0.getName());
  }
}
