/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 07 11:39:34 GMT 2024
 */

package uk.ac.sheffield.com1003.cafe.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.exceptions.RecipeNotFoundException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RecipeNotFoundException_ESTest extends RecipeNotFoundException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RecipeNotFoundException recipeNotFoundException0 = new RecipeNotFoundException();
  }
}
