/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 09 15:53:32 GMT 2024
 */

package uk.ac.sheffield.com1003.cafe.ingredients;

import org.junit.Test;

import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.ingredients.Coffee;
import uk.ac.sheffield.com1003.cafe.ingredients.Milk;
import uk.ac.sheffield.com1003.cafe.ingredients.Syrup;
import uk.ac.sheffield.com1003.cafe.ingredients.Unit;
import uk.ac.sheffield.com1003.cafe.ingredients.Water;

public class Ingredient_ESTest {

    @Test(timeout = 4000)
    public void test00() throws Throwable {
        Coffee coffee0 = new Coffee();
        String string0 = coffee0.toString();
        assertEquals("Coffee [unit=GR, amount=8, decaf=false]", string0);
    }

    @Test(timeout = 4000)
    public void test01() throws Throwable {
        Water water0 = new Water();
        water0.name = null;
        String string0 = water0.getName();
        assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test02() throws Throwable {
        Coffee coffee0 = new Coffee();
        String string0 = coffee0.getName();
        assertEquals("Coffee", string0);
    }

    @Test(timeout = 4000)
    public void test03() throws Throwable {
        Water water0 = new Water(0);
        water0.name = "";
        String string0 = water0.getName();
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test04() throws Throwable {
        Milk milk0 = new Milk(0);
        int int0 = milk0.getAmount();
        assertEquals(0, int0);
    }

    @Test(timeout = 4000)
    public void test05() throws Throwable {
        Water water0 = new Water((-3138));
        int int0 = water0.getAmount();
        assertEquals((-3138), int0);
    }

    @Test(timeout = 4000)
    public void test06() throws Throwable {
        Syrup syrup0 = new Syrup();
        syrup0.name = null;
        // Undeclared exception!
        try {
            syrup0.equals(syrup0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
        }
    }

    @Test(timeout = 4000)
    public void test07() throws Throwable {
        Coffee coffee0 = new Coffee();
        boolean boolean0 = coffee0.equals(coffee0);
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test08() throws Throwable {
        Syrup syrup0 = new Syrup();
        Object object0 = new Object();
        boolean boolean0 = syrup0.equals(object0);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test09() throws Throwable {
        Syrup syrup0 = new Syrup();
        boolean boolean0 = syrup0.equals((Object) null);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test10() throws Throwable {
        Water water0 = new Water();
        Unit unit0 = water0.getUnit();
        assertEquals(Unit.ML, unit0);
    }

    @Test(timeout = 4000)
    public void test11() throws Throwable {
        Milk milk0 = new Milk();
        int int0 = milk0.getAmount();
        assertEquals(100, int0);
    }
}
