/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 21 18:27:26 GMT 2023
 */

package uk.ac.sheffield.com1003.cafe.junit4.evosuite.ingredients;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.ingredients.*;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Ingredient_ESTest extends Ingredient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Syrup syrup0 = new Syrup((String) null);
      String string0 = syrup0.toString();
      assertEquals("Syrup [unit=ML, amount=10, flavour=null]", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Milk milk0 = new Milk();
      Unit unit0 = milk0.getUnit();
      assertEquals(Unit.ML, unit0);
  }

//  @Test(timeout = 4000)
//  public void test02()  throws Throwable  {
//      Milk milk0 = new Milk();
//      milk0.name = null;
//      String string0 = milk0.getName();
//      assertNull(string0);
//  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Milk milk0 = new Milk();
      String string0 = milk0.getName();
      assertEquals("Milk", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Syrup syrup0 = new Syrup();
//      syrup0.name = "";
      String string0 = syrup0.getName();
      assertEquals("Syrup", string0);
  }

//  @Test(timeout = 4000)
//  public void test05()  throws Throwable  {
//      Coffee coffee0 = new Coffee();
//      coffee0.amount = 0;
//      int int0 = coffee0.getAmount();
//      assertEquals(0, int0);
//  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Water water0 = new Water();
      int int0 = water0.getAmount();
      assertEquals(30, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Coffee coffee0 = new Coffee(-382, true);
//      coffee0.amount = (-382);
      int int0 = coffee0.getAmount();
      assertEquals((-382), int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Coffee coffee0 = new Coffee(1530);
      boolean boolean0 = coffee0.equals(coffee0);
      assertTrue(boolean0);
  }

//  @Test(timeout = 4000)
//  public void test09()  throws Throwable  {
//      Coffee coffee0 = new Coffee();
//      Syrup syrup0 = new Syrup();
//      syrup0.name = null;
//      // Undeclared exception!
//      try {
//        syrup0.equals(coffee0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//      }
//  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Syrup syrup0 = new Syrup("Water [unit=ML, amount=1]");
      boolean boolean0 = syrup0.equals("Water [unit=ML, amount=1]");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Syrup syrup0 = new Syrup((String) null);
      boolean boolean0 = syrup0.equals((Object) null);
      assertFalse(boolean0);
  }
}
