/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Sep 26 14:35:07 GMT 2023
 */

package uk.ac.sheffield.com1003.cafe.evosuite.branch.exceptions;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TooManyIngredientsException_ESTest_scaffolding {
  // Empty scaffolding for empty test suite
}
