/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 21 16:02:18 GMT 2023
 */

package uk.ac.sheffield.com1003.cafe.junit4.evosuite.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sheffield.com1003.cafe.exceptions.CafeOutOfCapacityException;
import uk.ac.sheffield.com1003.cafe.junit4.evosuite.exceptions.CafeOutOfCapacityException_ESTest_scaffolding;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CafeOutOfCapacityException_ESTest extends CafeOutOfCapacityException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CafeOutOfCapacityException cafeOutOfCapacityException0 = new CafeOutOfCapacityException();
  }
}
